[package]
name = "pex"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2.workspace = true
async-recursion = "1.1.1"
eyre = "0.6.12"
tokio = { version = "1", features = [
    "macros",
    "time",
    "rt-multi-thread",
    "signal",
    "fs",
] }
